[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --ignore-engines"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma db push && node .output/server/index.mjs"
